Podium-1909-GH/Podium

script/seed.js, server/db/models/index.js, server/db/models/speech.js, utils/fillerwords.js
=> Database schema #6

client/components/recording-screen.js, client/store/index.js, client/store/speech.js, server/api/users.js, server/db/models/speech.js
---
created ability to transcribe and send to database
=> Transcribe audio #2

client/components/home.js, client/components/index.js, client/components/log-in-auth-form.js, client/components/navbar.js, client/components/sign-up-auth-form.js, client/components/user-home.spec.js, client/components/user-profile.js, client/routes.js, client/store/user.js, server/auth/google.js, server/auth/index.js, server/db/models/speech.js
=> Signup local #6

client/components/user-dashboard.js, client/components/welcome-page.js
in welcome page, the buttons to record page and dashboard page work now
=> refactor: welcome page buttons links work

client/components/recording-screen.js, client/components/speech-overview.js, client/store/index.js, client/store/speech.js, client/store/speeches.js, server/api/users.js
---
get speech backend written, overview page built
=> Get speech routes #17

client/components/log-in-auth-form.js, client/components/navbar.js, client/components/sign-up-auth-form.js, client/components/welcome-page.js, public/index.html, public/style.css
=> Style auth form

client/components/navbar.js, client/components/speech-overview.js, public/style.css
=> style: updated the navbar

client/components/dashboard-wpm-d3.js, client/components/dashboard-wpm-wrapper.js, client/components/navbar.js, client/components/user-dashboard.js, client/store/user.js, public/index.html, public/style.css, script/seed.js, server/auth/google.js, utils.js
---
Dashboard wpm average component + restructured seed file + small changes
=> Dashboard wpm #25

client/components/dashboard-filler-d3.js, client/components/dashboard-filler-wrapper.js, client/components/user-dashboard.js
=> feat: dashboard filler chart and top 5

client/components/navbar.js, client/routes.js, public/style.css
=> Edit navbar #46

client/components/dashboard-main-d3.js, client/components/user-profile-edit.js, client/components/user-profile.js, client/routes.js, public/style.css
- fix: user profile button so it links to edit profile
- style: centered content on user profile views
=> refactor: user profile and edit profile features separated

client/components/dashboard-sentiment-wrapper.js, client/components/speech-sentiment-d3.js, client/components/speech-sentiment-wrapper.js
=> style: pie chart recolor

client/components/dashboard-sentiment-wrapper.js, client/components/speech-sentiment-wrapper.js
=> Speech pie dataflow

client/components/speech-overview.js
=> fix: render window to the top

client/components/speech-transcript.js
=> fix: edit transcript dialog title

server/auth/google.js
=> fix: proxy on google callback

client/components/speech-overview.js, client/components/speech-sentiment-wrapper.js, client/components/speech-wpm-wrapper.js, client/store/speech.js, server/api/users.js
=> fix: security patch

server/api/users.js
=> fix: speeches sorted

README.md, server/db/models/index.js, server/db/models/speech.js, server/db/models/user.js, server/db/models/word.js
=> added comments about databases

client/components/dashboard-main-d3.js, client/components/speech-filler-d3.js
- added documentation comments on d3 bar chart files
=> docs: added bar chart comments
